version: "2"
services:
  app:
    build: ./app
    container_name: "app"
    ports:
      - "8000:5000"
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - '6379'
  
  worker:
    build: ./worker
    container_name: worker
    command: rq worker --with-scheduler -u "redis://redis:6379"
    deploy:
      replicas: 1
    depends_on:
      - redis