version: "2"
services:
  app:
    build: ./app
    container_name: ml-server
    ports:
      - 4000:4000
    volumes:
      - ml-server:/home/node/app
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - '6379'
  
  worker:
    build: ./worker
    command: rq worker --with-scheduler -u "redis://redis:6379"
    deploy:
      replicas: 3
    depends_on:
      - redis
    volumes:
      - ml-server:/home/node/app

volumes:
  ml-server: