version: "2"
services:
  app:
    build: ./app
    container_name: "app"
    ports:
      - "5000:5000"
    volumes:
      - myapp:/home/node/app
    networks:
      - default
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - '6379'
    networks:
      - default
  
  worker:
    build: ./worker
    container_name: worker
    command: rq worker --with-scheduler -u "redis://redis:6379"
    deploy:
      replicas: 1
    depends_on:
      - redis
    volumes:
      - myapp:/home/node/app
    networks:
      - default

volumes:
  myapp:

networks:
  default:
    name: statusNetwork
    driver: bridge